oraichain/oraiscan-frontend

src/components/Header/NavBar/Dialog/AddAddressDialog.js

Task: 
- https://oraichain.atlassian.net/browse/ORF-296
Description:

fix: fix placeholder with prefix

---

src/components/Wallet/StatusBar/StatusBar.js

Description:
- fix missing icon svg by missiong default attribute
Link reference:
- https://stackoverflow.com/questions/59070216/webpack-file-loader-outputs-object-module

fix require module

---

src/containers/Proposals/Proposals.js

Description:
- add warning when create proposal

feat: add warning when create proposal

---

src/components/ProposalDetails/DetailsCard/DetailsCard.js

Description:
- add `contract` field to display for proposal detail card with type `/cosmwasm.wasm.v1.UpdateAdminProposal`

fix: add contract field to proposal detail

---

src/GlobalStyles.js
src/components/Proposals/ProposalsTable/ProposalsTable.js
src/components/Proposals/TopProposalCardList/ChartCard/ChartCard.js
src/components/Proposals/TopProposalCardList/ChartCard/ChartCard.module.scss
src/components/Proposals/TopProposalCardList/ChartCard/ChartCardSkeleton.js
src/components/Proposals/TopProposalCardList/ChartCard/index.js
src/components/Proposals/TopProposalCardList/TopProposalCardList.js
src/components/Proposals/TopProposalCardList/TopProposalCardList.module.scss
src/components/Proposals/TopProposalCardList/TopProposalCardListSkeleton.js
src/constants/themes.js
src/containers/Proposals/CreateProposal.js
src/containers/Proposals/Proposals.js
src/containers/Proposals/constant.js
src/icons/Proposals/ViewMoreProposalIcon.js

Update: change UI Proposal list ( update layout skeleton )

Update/update UI proposal

---

src/components/Proposals/TopProposalCardList/TopProposalCardList.js
src/components/Proposals/TopProposalCardList/TopProposalCardList.module.scss

- Update responsive Proposal

---

src/components/Block/CountdownRemainingBlock/Countdown.js
src/components/Block/CountdownRemainingBlock/CountdownRemainingBlock.js
src/components/Block/CountdownRemainingBlock/CountdownRemainingBlock.module.scss
src/components/Block/CountdownRemainingBlock/index.js
src/components/Block/CurrentBlock/CurrentBlock.js
src/components/Block/CurrentBlock/CurrentBlock.module.scss
src/components/Block/CurrentBlock/index.js
src/components/common/StatusBox/StatusBox.js
src/containers/Block/Block.js
src/hooks/index.js
src/hooks/useCheckFutureBlock.js

feat: add countdown UI for future block.

feat: add countdown UI for future block.

---

src/components/Tx/TxData/TxMessage/TxMessage.js
src/components/Tx/TxData/TxMessage/TxMessageContent.js

update: add IBC progress for MsgExecute

update: add IBC progress for MsgExecute

---

src/components/Account/AssetsTable/AssetsTable.js
src/components/Ibc/DelegationTable/DelegationTable.js
src/components/Tx/TxData/TxMessage/IBCProgress/IBCProgress.js
src/components/Tx/TxData/TxMessage/TxMessage.js
src/components/Tx/TxData/TxMessage/TxMessageContent.js
src/helpers/helper.js

fix: update IBC denom

---

src/constants/consts.js

update: change url api get price from coinmarketcap to orai market

update: change url api get price from coinmarketcap to orai market

---

src/components/Dashboard/TransactionCardList/TransactionCardList.module.scss
src/containers/ValidatorList/ValidatorList.js

fix: fix error load Validator data & responsive txs in Dashboard

fix: fix error load Validator data & responsive txs in Dashboard

---

src/components/SmartContracts/SmartContractTable/SmartContractTable.js
src/components/ValidatorList/AccountTable/AccountTable.js

fix:  fix overflow display in smart-contract and accounts

ORF-846: fix overflow display in smart-contract and accounts

---

src/containers/VerifiedContract/ComponentContract/ComponentContract.js
src/containers/VerifiedContract/ContractInteraction.js
src/containers/VerifiedContract/ReadContract/ReadContract.js
src/containers/VerifiedContract/WriteContract/WriteContract.js

- Update result schema to json viewer

update result schema to json viewer

---

src/containers/ProposalsDetail/ProposalDepositModal.js

remove fee, gas setting not use in deposit proposal

remove fee, gas setting not use in deposit proposal

---

src/components/Account/TransactionCard/TransactionCard.js
src/components/Wallet/CwToken/CwToken.js
src/components/Wallet/CwToken/CwToken.module.scss
src/constants/consts.js
src/containers/Account/Account.js
src/containers/ExportData/ExportData.js

Update download csv cw20 transaction tab account

Update download csv cw20 transaction tab account

---

src/components/ProposalDetails/DetailsCard/DetailsCard.js
src/components/ProposalDetails/DetailsCard/DetailsCard.module.scss

What is the purpose of these changes?
Fix UI proposal detail.

Fix UI proposal detail

---

src/constants/consts.js
src/containers/VerifiedContract/CodeVerifiedContract/CodeContract.js
src/containers/VerifiedContract/CodeVerifiedContract/CodeContract.module.scss
src/containers/VerifiedContract/ContractCard/ContractCard.js
src/containers/VerifiedContract/VerifiedContract.js
src/lib/api.js

What is the purpose of these changes?
- This feature allow creator of smart contract upload schema contract.
Brief changelog:
- Get nonce to verify signature of contract's owner then upload schema contract.
Documentation and Release Note
- Does this PR introduces new features or user-facing behaviour changes? Yes
- How is the feature or changes documented? No

Allow creator upload schema for smart contract

---

.env.example
src/config.js

What is the purpose of these changes?
- Add Url Testnet Verify Contract
Documentation and Release Note
- Does this PR introduces new features or user-facing behaviour changes? Yes
- How is the feature or changes documented? No

[Feature] - Add Url Testnet Verify Contract

---

src/components/Footer/Footer/Footer.js

What is the purpose of these changes?
- Update social link.
Brief changelog:
- Update Github and Discord link in footer.
Documentation and Release Note
- Does this PR introduces new features or user-facing behaviour changes? No
- How is the feature or changes documented? No

hotfix: update social link

---

src/components/ProposalDetails/DetailsCard/DetailsCard.js
src/helpers/helper.js

chore: move isJsonString func to global helpers

chore: move isJsonString func to global helpers

---

src/containers/Router/Router.js
src/containers/ValidatorList/ValidatorList.js

- Fixed error load chunk error occur after deploy updates
Brief changelog:
- Add callback function to handle lazy import: force window refresh to reload new code if cannot load component.

fix: fixed error load chunk

---

src/containers/Tabs/Tabs.css

- Fix responsive Tabs in TogglePageBar: when hover it can't dropdown.

fix responsive Tabs in TogglePageBar

---

src/components/Wallet/NFTToken/NFTCard/NFTCard.js
src/components/Wallet/NFTToken/NFTCard/NFTCard.module.scss
src/components/Wallet/NFTToken/NFTCard/NFTCardSkeleton.js
src/components/Wallet/NFTToken/NFTCard/index.js
src/components/Wallet/NFTToken/NFTTable/NFTTable.js
src/components/Wallet/NFTToken/NFTTable/NFTTable.module.scss
src/components/Wallet/NFTToken/NFTTable/NFTTableSkeleton.js
src/components/Wallet/NFTToken/NFTTable/index.js
src/components/Wallet/NFTToken/NFTToken.js
src/components/Wallet/NFTToken/NFTToken.module.scss
src/components/Wallet/NFTToken/index.js
src/components/Wallet/Tabs/Tabs.js
src/containers/Wallet/Wallet.js
src/lib/api.js

- Add table NFT Txs into page wallet

add NFT Txs tab in page: /wallet

---

src/components/Block/CountdownRemainingBlock/Countdown.js

- Display time use local timezong instead hardcode +7 in future block
Does this PR introduces new features or user-facing behaviour changes? Yes
How is the feature or changes documented? No

Use local timezone instead hardcode

---

src/components/Dashboard/TransactionTable/TransactionTable.js
src/components/Dashboard/TransactionTable/TransactionTable.module.scss
src/components/Dashboard/TransactionsCard/TransactionsCard.js
src/containers/TxList/TxList.js

What are the purpose of the change?
- Fix value callback: "before, type" in API called when click on **Pagination button** of **Table Transactions** in **Dashboard Page**

fix Transaction Table in Dashboard

---

src/containers/Proposals/CreateProposal.js

- Change default type proposal to text proposal

update: change default type proposal to text proposal

---

src/components/ProposalDetails/DetailsCard/DetailsCard.js

fix details proposal

---

public/index.html

add clarity

---

.eslintrc.json
package.json
src/components/Tx/TxData/TxMessage/TxMessage.js
src/components/Tx/TxData/TxMessage/TxMessageContent.js
src/components/TxList/TransactionCardList/TransactionCardList.js
src/components/TxList/TransactionTable/TransactionTable.js
src/helpers/helper.js
yarn.lock

feat: show info for future trade

---

src/components/TxList/TransactionCardList/TransactionCardList.js
src/components/TxList/TransactionTable/TransactionTable.js
src/helpers/helper.js
src/hooks/usePreload.js
src/lib/api.js
src/store/modules/blockchain.js

fix: fixprice usdt in list)

---

src/components/common/StatusBox/StatusBox.js

fix tooltip text Infration ->  Inflation

fix: text tooltip

---

src/components/TxList/TransactionCardList/TransactionCardList.js
src/components/TxList/TransactionTable/TransactionTable.js
src/components/TxList/TransactionTable/TransactionTable.module.scss
src/helpers/helper.js
src/helpers/transaction.js

fix: fix amount ORAI on table

---

src/components/ReactJson/index.js
src/components/Tx/TxData/TxMessage/TxMessage.js
src/components/Tx/TxData/TxMessage/TxMessage.module.scss

feat: format string amount with currency

---

src/components/Tx/TxData/TxMessage/TxMessage.js
src/components/Tx/TxData/TxMessage/TxMessage.module.scss

fix: map all events

---

src/components/Tx/TxData/TxMessage/TxMessage.module.scss

fix: width td

---

src/components/Wallet/CwToken/CwCard/CwCard.js

fix: link accout mobile mode

---

src/components/ValidatorList/ValidatorCardList/ValidatorCardList.js

- Use correct APR for calculate reward when delegate ORAI

fix: use correct APR for calculate reward when deletate ORAI

---

src/components/ProposalDetails/Depositors/Depositors.js
src/containers/ProposalsDetail/ProposalsDetail.js
src/hooks/useFetchLCD.js

- add missing fields to detail.
- add list depositors.

fix: detail proposal
